from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from dotenv import load_dotenv
from langchain_community.retrievers import BM25Retriever
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_pinecone import PineconeVectorStore
from langchain_core.messages import HumanMessage, AIMessage
from pydantic import BaseModel, Field
import cohere
from pathlib import Path
import os

# Import loaders from ingest module to keep BM25 in sync with Pinecone
from rag_basics.langchain_ingest_pinecone import load_content_chunks, load_link_chunks

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(ENV_PATH)

INDEX_NAME = "jianuo-dev-v1"

# --- Clients ---
co = cohere.ClientV2(api_key=os.getenv("COHERE_API_KEY"))
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)

# --- Retrievers ---
vectorstore = PineconeVectorStore(
    index_name=INDEX_NAME,
    embedding=embeddings,
)
semantic_retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

# BM25 covers BOTH content and link chunks (方案 A)
_all_docs_for_bm25 = load_content_chunks() + load_link_chunks()
bm25_retriever = BM25Retriever.from_documents(_all_docs_for_bm25)
bm25_retriever.k = 3


# --- Structured output schema (选项 Z) ---
class RagOutput(BaseModel):
    """Structured output for the RAG chain.
    LLM decides the natural language answer AND which link resources to cite.
    URL is fetched from retrieved docs by code, never generated by LLM.
    """
    answer: str = Field(description="自然语言回答，用中文")
    cited_link_ids: list[str] = Field(
        default_factory=list,
        description=(
            "If the answer references any link-type resources from the context, "
            "list their resource_id values here. Empty list if no link is cited."
        ),
    )


# --- Prompt ---
prompt = ChatPromptTemplate.from_messages([
    ("system", """你是移民咨询助手,只根据提供的 Context 回答用户问题,不要编造。
如果 Context 里没有答案,answer 字段说"我没有相关信息",cited_link_ids 留空。

Context 里的 chunk 有两种类型:

1. content 类型: 包含政策/知识文本, 用于生成 answer

2. link 类型: 代表一个可下载的资源。header 里会标注具体资源类型:
   - link(fee_template): 收费模版
   - link(info_form): 信息收集表
   - link(guide): 指导手册
   - link(material_list): 材料收集清单(压缩包目录)
   - link(consent_form): 同意书/同意函
   - link(fill_instructions): 填写方式说明
   - link(template): 通用模板
   
   每个 link chunk 会显示 resource_id, 用于在 cited_link_ids 里引用。
   
   严格规则(必须遵守):
   - 不要在 answer 里输出 URL
   - 不要在 answer 里输出 resource_id 字符串(如 "visa_study_first_minor_material_list")
   - 不要在 answer 里说"请参考以下链接"然后列出 resource_id
   - answer 只用自然语言引导用户(如"具体材料清单请见下方相关资源"),链接由系统自动展示
   - 所有需要引用的资源, resource_id 只放进 cited_link_ids 字段

判断规则:
- 用户问"是什么/怎么样/为什么" → 主要用 content 生成 answer
- 用户问"表格/模板/在哪下载/给我 XX 文件/需要什么材料" → 主要引用 link, answer 里做简短说明
- 混合意图 → answer 给知识说明, cited_link_ids 附上相关资源"""),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "Context:\n{context}\n\nQuestion: {question}"),
])


# --- Helpers ---
def _format_chunk_index(raw):
    if isinstance(raw, (int, float)):
        return int(raw)
    return raw


def format_docs(docs) -> str:
    parts = []
    for doc in docs:
        md = doc.metadata
        source = md.get("source", "unknown")
        chunk_index = _format_chunk_index(md.get("chunk_index", "?"))
        resource_type = md.get("resource_type", "content")

        # 新判断:content 是知识文本,其他都是 link 类资源
        is_link = resource_type != "content"
        
        if is_link:
            resource_id = md.get("resource_id", "")
            # 把 resource_type 也告诉 LLM,帮助它判断资源类型
            header = (
                f"[来源:{source}, 第{chunk_index}块, "
                f"类型:link({resource_type}), resource_id:{resource_id}]"
            )
        else:
            header = f"[来源:{source}, 第{chunk_index}块, 类型:content]"

        parts.append(f"{header}\n{doc.page_content}")
    return "\n\n".join(parts)


def hybrid_retriever(question: str, k: int) -> list:
    semantic_docs = semantic_retriever.invoke(question)
    bm25_docs = bm25_retriever.invoke(question)
    seen = set()
    combined = []
    for doc in semantic_docs + bm25_docs:
        if doc.page_content not in seen:
            seen.add(doc.page_content)
            combined.append(doc)
    return combined[:k]


def retrieve(
    query: str,
    use_bm25: bool = True,
    use_dense: bool = True,
    use_rerank: bool = True,
    top_k: int = 3,
) -> list:
    """Unified retrieval interface for production + ablation eval.
    
    Args:
        query: Search query string.
        use_bm25: Include BM25 lexical retrieval.
        use_dense: Include Pinecone dense retrieval.
        use_rerank: Apply Cohere cross-encoder rerank as final stage.
        top_k: Number of docs to return.
    
    Returns:
        List of Document objects ordered by relevance, len <= top_k.
    """
    # Validate: at least one retrieval strategy must be enabled
    if not (use_bm25 or use_dense):
        raise ValueError("At least one retrieval strategy (BM25 or dense) must be enabled.")
    
    # Determine intermediate k (before rerank)
    # 如果要 rerank, 粗排层多召回一些 (6 个) 给 rerank 挑; 否则直接要 top_k
    intermediate_k = 6 if use_rerank else top_k
    
    # Reset BM25 k to default before branching (avoid stale state from prior calls)
    # Reset shared retriever state before branching (avoid stale k from prior calls).
    # NOTE: mutating shared singleton attrs is not ideal — tech debt to refactor
    # to per-call similarity_search() bypassing retrievers.
    bm25_retriever.k = 3
    semantic_retriever.search_kwargs["k"] = 3

    # Branch 1: hybrid (both BM25 and dense)
    if use_bm25 and use_dense:
        docs = hybrid_retriever(query, intermediate_k)
    
    # Branch 2: BM25 only
    elif use_bm25 and not use_dense:
        bm25_retriever.k = intermediate_k
        docs = bm25_retriever.invoke(query)
    
    # Branch 3: dense only
    elif use_dense and not use_bm25:
        semantic_retriever.search_kwargs["k"] = intermediate_k
        docs = semantic_retriever.invoke(query)
    
    # Rerank stage (optional)
    if use_rerank:
        docs = rerank_docs(query, docs, top_n=top_k)  # 替换这行
    else:
        docs = docs[:top_k]  # 替换这行
    
    return docs

def rerank_docs(question: str, docs: list, top_n: int = 3) -> list:
    if not docs:
        return []
    texts = [doc.page_content for doc in docs]
    response = co.rerank(
        model="rerank-v3.5",
        query=question,
        documents=texts,
        top_n=top_n,
    )
    return [docs[result.index] for result in response.results]

def rewrite_query_for_retrieval(question: str, history: list) -> str:
    """Rewrite a follow-up question into a self-contained query using chat history.
    
    Only used for retrieval. Original question is preserved for answer generation.
    """
    if not history:
        return question  # First turn, no rewriting needed
    
    history_str = "\n".join(
        f"{'用户' if isinstance(m, HumanMessage) else '助手'}: {m.content}"
        for m in history
    )
    
    rewrite_prompt = f"""基于以下对话历史,把用户最新问题改写成一个可以独立理解的完整问题。
- 解析所有代词(它/这个/那个/他们等)为具体名词
- 补齐省略的主语或上下文
- 保持原问题的核心意图不变
- 只输出改写后的问题,不要任何解释

对话历史:
{history_str}

最新问题: {question}

改写后的问题:"""
    
    result = llm.invoke(rewrite_prompt)
    rewritten = result.content.strip()
    print(f"[rewrite] original:  {question}")
    print(f"[rewrite] rewritten: {rewritten}")
    return rewritten


# --- Chain (with structured output) ---
structured_llm = llm.with_structured_output(RagOutput)
rag_chain = prompt | structured_llm

store: dict[str, list] = {}

def get_history(session_id: str) -> list:
    """Return message list for a session. Create if not exists."""
    if session_id not in store:
        store[session_id] = []
    return store[session_id]


def ask(question: str, session_id: str = "default") -> dict:
    """Main RAG entry point with manual chat history + query rewriting."""
    try:
        # Get chat history FIRST (needed for query rewriting)
        history = get_history(session_id)
        
        # Rewrite query for retrieval using history (no-op if history is empty)
        retrieval_query = rewrite_query_for_retrieval(question, history)
        
        # Use rewritten query for retrieval; original question for answer generation
        docs = retrieve(retrieval_query)  # 或 retrieve(question), 保持原变量名
        context = format_docs(docs)

        # Invoke chain with explicit chat_history
        result: RagOutput = rag_chain.invoke({
            "context": context,
            "question": question,
            "chat_history": history,
        }) # type: ignore

        # Manually append to history AFTER successful invocation
        history.append(HumanMessage(content=question))
        history.append(AIMessage(content=result.answer))

        # Build sources
        source_info = [
            f"{doc.metadata.get('source', 'unknown')} 第{_format_chunk_index(doc.metadata.get('chunk_index', '?'))}块"
            for doc in docs
        ]

        # Resolve cited_link_ids -> full link details (guardrail against hallucinated IDs)
        retrieved_link_map = {
            doc.metadata["resource_id"]: doc
            for doc in docs
            if doc.metadata.get("resource_type") != "content"   # 改判断方向
            and doc.metadata.get("resource_id")
        }
        links = []
        for lid in result.cited_link_ids:
            if lid in retrieved_link_map:
                md = retrieved_link_map[lid].metadata
                links.append({
                    "title": md.get("resource_title", ""),
                    "url": md.get("resource_url", ""),
                    "resource_id": lid,
                })

        return {
            "answer": result.answer,
            "sources": source_info,
            "links": links,
        }
    except Exception as e:
        raise Exception(f"Error during question answering: {str(e)}")
    

def retrieve_kb_context(question: str) -> str:
    """
    Use to search the Canadian immigration knowledge base, which contains
    policy content (visa programs, eligibility criteria) AND link resources
    (forms, templates, guides, official IRCC PDFs).

    Args:
        question: A self-contained query string with pronouns resolved.

    Returns:
        Retrieved context chunks with type annotations (content or link).
    """
    try:
        docs = rerank_docs(question, hybrid_retriever(question, k=6), top_n=3)
        return f"Retrieved context from knowledge base:\n\n{format_docs(docs)}"
    except (ConnectionError, TimeoutError):
        return "知识库检索暂时不可用(网络连接问题)。建议稍后重试。"
    except Exception as e:
        print(f"[ERROR] retrieve_kb_context: {type(e).__name__}: {e}")
        return "知识库检索遇到未知问题, 建议稍后重试或联系支持团队。"


if __name__ == "__main__":
    print("欢迎使用移民咨询系统! 输入 'q' 退出。")
    while True:
        user_question = input("请输入你的问题: ")
        if user_question.lower() == "q":
            print("Exiting the program.")
            exit(0)
        result = ask(user_question, session_id="default")
        print(f"\n答案: {result['answer']}")
        if result["links"]:
            print("\n相关资源:")
            for link in result["links"]:
                print(f"  - {link['title']}: {link['url']}")
        print(f"\n来源: {result['sources']}\n")